sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "12.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - cd redfox-sport-ui
  - npm install
  - ng build --prod
  - npm run lint
  - npm run test
deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    secure: "m7zqRxorBJDImdACiB9LLjYJNne1QsLYFTjuKbb/hgvk+jmj6BCKaRMajoo7dR41Wq+3U397vj1Q/kAMn92Umn/dHWEyhQor9XWUnU2yJXCS+cJhB80q7EjkDmw30MvIjyX8zcrMZky3AJ3hHVKlk7GzKzLKXPWkK3BynCHZXFW4Q7Tq/PlPc3lyCkC3Ep/GhqntrPldD/Ka4/yyFoe/HTj5o+B0k+UNP7IWT/SxdHYY/GBxVlAGqPHfIkto4H6z0UA+RAieWagJcNDYQgiBIC3W+vmA2h0NZ0CFcO0sfD00EoyuG7JHpTFcv+4QnypCzhWdU5c+1FfdztUsn4B07UoZuHlA3yCSQyXBdfVV2QfCqwgeJYB6oc+2akvlR/3iLw4diYM4jelEi2L/r6tzFJ17RrTuAXeO2cCE55u07B99bUpkD1KZDlAe9RE+mVi0tlNuT04B8QKD1BdhBoRGK7B/f6zhGzf1bEo+1u2tZS3eul+6GFOWIn3Ouyf+nP55O/074ivdCo9Ybj4X3GOhF79z8uhrV94j7NzwulBw8qv08aMthIEpFiblK7kLkczXAkqoYdduI+1gqtP423LIUq5fa+K71k/4MuRdizaCp4n91b9cTRng3EGlBCDyWhYBCo+gTRP0tE2uef/0vd/eCdn6PhtdYidEHm4kCDA3ons="